version: '3.8'

services:
  api:
    build: .
    container_name: agrivision_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    # Removed 'depends_on' since MinIO is external
    networks:
      - agrivision_net

# Removed 'minio' service and 'volumes' block

networks:
  agrivision_net:
    driver: bridge