"""add image_hash to scans

Revision ID: 22a839181dfc
Revises: 1a0db1146e0b
Create Date: 2025-12-09 18:54:02.890723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a839181dfc'
down_revision: Union[str, Sequence[str], None] = '1a0db1146e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('image_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_scans_image_hash'), 'scans', ['image_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_image_hash'), table_name='scans')
    op.drop_column('scans', 'image_hash')
    # ### end Alembic commands ###
